### ISSUE TITLE
Report humidity

### ISSUE THREAD

**Issue by itsits** [dlarrick/hass-kumo#93] opened 2022-11-18 20:41 UTC
PAC-USWHS003-TH-1 have humidity sensors exposed through kumo cloud. Has anyone looked at exposing them?

**Comment by dlarrick** [comment] 2022-11-18 22:45
The humidity from these remote sensors is reported as an attribute on the indoor unit to which it's connected. I know, I have one. 

![image](https://user-images.githubusercontent.com/11030293/202815476-ff277766-7201-44bc-b4c2-0f41a575a589.png)

It's easy enough to use a template sensor to turn an attribute into a sensor that nobody has bothered to expose it as a sensor directly. That said, I'd accept a pull request to do so.

**Comment by dlarrick** [comment] 2022-11-27 15:08
Closing this as a duplicate of #38 . Patches welcome.

**Closed by dlarrick** 2022-11-27 15:08 UTC
