### ISSUE TITLE
No temperature setting in logbook

### ISSUE THREAD

**Issue by lychee128** [dlarrick/hass-kumo#87] opened 2022-08-20 20:01 UTC
I don't think this is a bug but wasn't sure where best to post this.  My logbook correctly captures HVAC mode changes (eg, cooling, fan) but no temperature settings are recorded.  For example, if I turn on my A/C and change the temperature from 80 to 75, the only entry in the logbook is the HVAC mode going to cool. There's no record of the old or new temperature setting.

Is there a way to access the temperature setting ("temperature" attribute) so I can record what times and temps the HVAC unit was set to?

**Comment by dlarrick** [comment] 2022-08-20 20:08
Please take this type of question to the [Kumo integration thread](https://community.home-assistant.io/t/mitsubishi-kumo-cloud-integration/121508) on the Home Assistant forum. I'm going to close this issue because it's definitely not a bug.

That said, the standard approach is to create a template sensor from the entity's attribute(s) of interest.

**Closed by dlarrick** 2022-08-20 20:08 UTC

**Comment by lychee128** [comment] 2022-08-20 20:11
Got it and thanks.
